server:
    port: 8888
spring:
      application:
        name: gateway-service
      cloud:
        discovery:
          enabled: true
#        gateway:
#          routes:
#            - id: parent
#              uri: http://localhost:8080
#              predicates:
#                - Path=/myGov_parent/**
#            - id: child_1
#              uri: http://localhost:8081
#              predicates:
#                - Path=/finance_ministry/**
#            - id: child_2
#              uri: http://localhost:8082
#              predicates:
#                - Path=/justice_ministry/**